name:                libraft
synopsis:            Raft consensus algorithm
category:            Distributed Systems
version:             0.4.1.0
github:              "adjoint-io/raft"
license:             BSD3
author:              "Adjoint Inc."
maintainer:          "info@adjoint.io"
copyright:           "2018-2019 Adjoint Inc."

extra-source-files:
- README.md
- ChangeLog.md
- postgres/entries.sql

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/adjoint-io/raft#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- mtl
- containers
- text
- concurrency >= 1.3.0.0
- transformers
- exceptions
- cereal
- random
- repline
- haskeline
- parsec
- attoparsec
- time
- network-simple
- bytestring
- word8
- network
- directory
- filepath
- cryptohash-sha256
- base16-bytestring
- lifted-base
- monad-control
- transformers-base
- atomic-write
- postgresql-simple
- file-embed
- dejafu >= 1.12.0.0
- stm
- async

default-extensions:
  NoImplicitPrelude
  OverloadedStrings
  LambdaCase

library:
  source-dirs: src
  ghc-options:
  - -fwarn-unused-binds
  - -fwarn-unused-imports

executables:
  raft-example:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - libraft
    - stm
    - postgresql-simple-url
    - optparse-applicative

tests:
  raft-test:
    main:                TestDriver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dejafu
    - libraft
    - process >= 1.6.3.0
    - QuickCheck
    - quickcheck-state-machine
    - tasty
    - tasty-dejafu
    - tasty-discover
    - tasty-expected-failure
    - tasty-hunit
    - tasty-quickcheck
    - tree-diff
