resolver: lts-13.3

packages:
- .

extra-deps:
- repline-0.2.0.0
- quickcheck-state-machine-0.4.3
- tree-diff-0.0.2
- split-0.2.3.3
- concurrency-1.6.2.0
- dejafu-1.12.0.0
- tasty-dejafu-1.2.1.0
- hunit-dejafu-1.2.1.0
- process-1.6.5.0
